import os
import time
from datetime import datetime
from dotenv import load_dotenv
from groq import Groq
from ddgs import DDGS
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch

load_dotenv()
api_key = os.environ.get("GROQ_API_KEY")

if not api_key:
    raise ValueError("GROQ_API_KEY not found in .env file!")

client = Groq(api_key=api_key)

AUTO_TOPICS = [
    "latest AI news 2026",
    "Pakistan economy news 2026",
    "cricket latest news 2026",
    "cryptocurrency prices 2026",
    "technology trends 2026"
]

def print_separator():
    print("="*60)

def search_web(topic):
    print(f"🌐 Searching web for: {topic}...\n")
    results = []
    try:
        with DDGS() as ddgs:
            for r in ddgs.text(topic, max_results=5):
                results.append(r['body'])
    except Exception as e:
        print(f"⚠️ Search failed for '{topic}': {e}")
        print("⏳ Retrying in 5 seconds...\n")
        time.sleep(5)
        try:
            with DDGS() as ddgs:
                for r in ddgs.text(topic, max_results=3):
                    results.append(r['body'])
        except Exception:
            print(f"❌ Skipping '{topic}' — search unavailable.\n")
            return ""
    return "\n\n".join(results)

def save_pdf(topic, summary):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = (
        f"research_{topic[:30]}_{timestamp}.pdf"
        .replace(" ", "_")
        .replace("?", "")
        .replace("!", "")
        .replace(":", "")
        .replace("/", "")
        .replace("\\", "")
    )

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=HexColor('#2C3E50'),
        spaceAfter=10
    )
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=HexColor('#7F8C8D'),
        spaceAfter=20
    )
    topic_style = ParagraphStyle(
        'CustomTopic',
        parent=styles['Normal'],
        fontSize=14,
        textColor=HexColor('#2980B9'),
        spaceAfter=10
    )
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor('#2C3E50'),
        spaceAfter=12,
        leading=18
    )

    content = []
    content.append(Paragraph("🤖 AI Research Agent", title_style))
    content.append(Paragraph("Powered by Groq AI + Live Web Search", subtitle_style))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph(f"<b>Topic:</b> {topic.upper()}", topic_style))
    content.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", subtitle_style))
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("<b>Research Summary</b>", topic_style))
    content.append(Spacer(1, 0.1*inch))

    for para in summary.split('\n'):
        if para.strip():
            content.append(Paragraph(para.strip(), body_style))

    content.append(Spacer(1, 0.5*inch))
    content.append(Paragraph(
        "Generated by AI Research Agent | Made by Abdul Wasay",
        subtitle_style
    ))

    doc.build(content)
    return filename

def research_topic(topic):
    conversation_history = [
        {
            "role": "system",
            "content": "You are a helpful research assistant. Summarize the web search results provided to you in a clear and concise way. Always base your answer on the search results given."
        }
    ]

    web_results = search_web(topic)

    if not web_results:
        return

    conversation_history.append({
        "role": "user",
        "content": f"Here are web search results about '{topic}':\n\n{web_results}\n\nPlease summarize this into a clear research summary."
    })

    print(f"🤖 AI is summarizing...\n")

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=conversation_history,
        max_tokens=700
    )

    summary = response.choices[0].message.content
    summary = summary.replace("**", "")

    print_separator()
    print(f"📌 TOPIC: {topic.upper()}")
    print(f"🕐 DATE:  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print_separator()
    print(f"\n{summary}\n")
    print_separator()

    pdf_file = save_pdf(topic, summary)
    print(f"✅ PDF saved to: {pdf_file}\n")

def run_auto_mode():
    print_separator()
    print("       🤖 AI RESEARCH AGENT v4.0")
    print("       Built by: Abdul Wasay")
    print("       AUTO MODE — No input needed!")
    print(f"       Researching {len(AUTO_TOPICS)} topics...")
    print_separator()

    for i, topic in enumerate(AUTO_TOPICS, 1):
        print(f"\n📋 Topic {i}/{len(AUTO_TOPICS)}: {topic}")
        research_topic(topic)

        if i < len(AUTO_TOPICS):
            print("⏳ Waiting 3 seconds before next topic...\n")
            time.sleep(3)

    print_separator()
    print(f"🎉 DONE! All {len(AUTO_TOPICS)} topics researched!")
    print(f"📁 Check your folder for PDF reports!")
    print("       Built by: Abdul Wasay")
    print_separator()

run_auto_mode()